### ISSUE TITLE
opening the app on Android 10 fails

### ISSUE THREAD

**Issue by spoo333** [mbruel/ClementineRemote#5]
Hello,
thanks for making this app. I installed it via the playstore. Unfortunately when I try to launch it, it aborts straight away. This is the error log:

time: 1613179407005
msg: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_Unwind_Resume" referenced by "/data/app/fr.mbruel.ClementineRemote-jQAs4geznuNvWT4eBMQkxQ==/lib/arm64/libprotobuf.so"...
stacktrace: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_Unwind_Resume" referenced by "/data/app/fr.mbruel.ClementineRemote-jQAs4geznuNvWT4eBMQkxQ==/lib/arm64/libprotobuf.so"...
	at java.lang.Runtime.load0(Runtime.java:938)
	at java.lang.System.load(System.java:1631)
	at org.qtproject.qt5.android.QtNative$3.run(QtNative.java:348)
	at org.qtproject.qt5.android.QtThread$2.run(QtThread.java:87)
	at org.qtproject.qt5.android.QtThread$1.run(QtThread.java:61)
	at java.lang.Thread.run(Thread.java:919)

Is the library libprotobuf.so missing? If so, how can I install it on my phone ...
thank you

**Comment by mbruel** [comment]
Hi,
hum, that's strange. libptotobuf.so should be included for both armv7 and arm64.
Google Play forces to create an package with both versions. I've never tried the 64 bit version, but I compiled libprotobuf for it so it should work...
You [can find here 2 apks, one for arm64, another one for armv7](https://files.fm/u/5przm4pqx). Normally both should run on a 64 bit architecture.
Could you please give it a try. First the arm64 version but I expect you'd have the same crash... Then the armv7 version, normally it should work.
I'll try to find some time next week to dig this issue a little bit.
I'll probably also release the v1.1 by the end of the month.

**Comment by spoo333** [comment]
Hi Mattieu,
thanks for getting back to me.
As you expected, the arm64 version doesn't work, just like the version on
GoogePlay. The armv7 version installs ok and I can run it. Thanks for the
software. Nice to see a new remote. Is it possible that downloads don't
work yet? When I try to change the download folder to [root folder]/Music
(and select overwrite files, just like in the old ClementineRemote), it
tells me "error creating download folder...". When I check the download
setting, the download folder has reverted to the previous/default
/storage/emulated/0/Download. In another window the software tells me that
the feature has not been implemented yet. I'll attach the screenshots.
Anway, thanks for all your work and effort.
Looking forward to v1.1.
All the best,
David

**Comment by mbruel** [comment]
It was a problem with the android ndk... 
After lots of headache, I've updated to android-ndk-r21e, rebuilt protobuf lib for arm64 and it seems to work \o/
The new version will arrive soon, I'm kind of finishing it :)

**Comment by spoo333** [comment]
Thanks for all your work. Looking forward to the new version
