### ISSUE TITLE
Android App closes immediately

### ISSUE THREAD

**Issue by jhard** [mbruel/ClementineRemote#6]
Opening the android app does show the ClemRemote app for a moment and it then immediately disappears without any interaction.

I'm using a Huawei P9 lite with Android 7.0. Is there anything I can do to provide helpful information?

**Comment by mbruel** [comment]
I suppose your device is using the 64 bit version.
I'm aware of it and finally find a solution ([cf here](https://forum.qt.io/topic/108704/building-protobuff-libs-for-android-64-bit-arm64-v8a-qt-5-12-4/24)).
I'm going to release a new release soon.

**Comment by mbruel** [comment]
The new version is released since a few weeks, I believe there is no more crash. Please reopen the ticket if so.
Cheers
